name: Build note to aliyun
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x] # 可以指定多个希望测试的Node.js版本

    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install npm dependencies
        run: yarn
      - name: Run build task
        run: yarn docs:build
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.ALIYUN_ECS_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.ALIYUN }} #引用之前创建好的secret
          local_path: './docs/.vitepress/dist'  # 对应我们项目build的文件夹路径
          remote_path: '/usr/local/nginx/html/doc'
          delete_remote_files: true #Be careful when use delete_remote_files, This will delete remote path folder and all files in it
          # sftp> put -r ./docs/.vitepress/dist /usr/local/nginx/html/doc
          # 这条命令的意思是将本地目录 ./docs/.vitepress/dist 下的所有文件和子目录递归地上传到远程服务器的 /usr/local/nginx/html/doc 目录中
