name: Build note to aliyun
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x] # 可以指定多个希望测试的Node.js版本

    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install npm dependencies
        run: yarn

      - name: Run build task
        run: yarn docs:build

      - name: Clean remote directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.ALIYUN_ECS_IP }}
          username: root
          key: ${{ secrets.ALIYUN }}
          script: |
            rm -rf /usr/local/nginx/html/doc/*

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_ECS_IP }}
          username: root
          key: ${{ secrets.ALIYUN }}
          source: './docs/.vitepress/dist/*'
          target: '/usr/local/nginx/html/doc/'

