name: Build note to aliyun
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x] # 可以指定多个希望测试的Node.js版本

    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install npm dependencies
        run: yarn
      - name: Run build task
        run: yarn docs:build
      - name: Deploy to Server
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.ALIYUN_ECS_IP }} # 你的阿里云公网地址
          user: root
          pass: ${{ secrets.ALIYUN }}
          connect_timeout: 10s
          local: 'docs/.vitepress/dist/*' # 要推送的文件夹，路径相对于代码仓库的根目录
          remote: /usr/local/nginx/html/doc # 打包后的 dist 文件夹将放在 /www/wwwroot/xxx
